# Data Preprocessing

In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
with open('2015.csv', 'r') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    data_2015 = list(spamreader)
    data_2015 = np.asarray(data_2015)
    df_2015 = pd.DataFrame(data=data_2015[1:], columns=data_2015[0])
    df_2015['Year'] = 2015
    df_2015 = df_2015[['Country', 'Year', 'Happiness Score']]
    df_2015.columns = ['Country', 'Year', 'Score']
    df_2015['Score'] = df_2015['Score'].astype(float)

In [3]:
df_2015

                      Country  Year  Score
0                 Switzerland  2015  7.587
1                     Iceland  2015  7.561
2                     Denmark  2015  7.527
3                      Norway  2015  7.522
4                      Canada  2015  7.427
5                     Finland  2015  7.406
6                 Netherlands  2015  7.378
7                      Sweden  2015  7.364
8                 New Zealand  2015  7.286
9                   Australia  2015  7.284
10                     Israel  2015  7.278
11                 Costa Rica  2015  7.226
12                    Austria  2015  7.200
13                     Mexico  2015  7.187
14              United States  2015  7.119
15                     Brazil  2015  6.983
16                 Luxembourg  2015  6.946
17                    Ireland  2015  6.940
18                    Belgium  2015  6.937
19       United Arab Emirates  2015  6.901
20             United Kingdom  2015  6.867
21                       Oman  2015  6.853
22                  Venezuela  2015  6.810
23                  Singapore  2015  6.798
24                     Panama  2015  6.786
25                    Germany  2015  6.750
26                      Chile  2015  6.670
27                      Qatar  2015  6.611
28                     France  2015  6.575
29                  Argentina  2015  6.574
..                        ...   ...    ...
128                   Myanmar  2015  4.307
129                   Georgia  2015  4.297
130                    Malawi  2015  4.292
131                 Sri Lanka  2015  4.271
132                  Cameroon  2015  4.252
133                  Bulgaria  2015  4.218
134                     Egypt  2015  4.194
135                     Yemen  2015  4.077
136                    Angola  2015  4.033
137                      Mali  2015  3.995
138       Congo (Brazzaville)  2015  3.989
139                   Comoros  2015  3.956
140                    Uganda  2015  3.931
141                   Senegal  2015  3.904
142                     Gabon  2015  3.896
143                     Niger  2015  3.845
144                  Cambodia  2015  3.819
145                  Tanzania  2015  3.781
146                Madagascar  2015  3.681
147  Central African Republic  2015  3.678
148                      Chad  2015  3.667
149                    Guinea  2015  3.656
150               Ivory Coast  2015  3.655
151              Burkina Faso  2015  3.587
152               Afghanistan  2015  3.575
153                    Rwanda  2015  3.465
154                     Benin  2015  3.340
155                     Syria  2015  3.006
156                   Burundi  2015  2.905
157                      Togo  2015  2.839

[158 rows x 3 columns]

In [4]:
with open('2016.csv', 'r') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    data_2016 = list(spamreader)
    data_2016 = np.asarray(data_2016)
    df_2016 = pd.DataFrame(data=data_2016[1:], columns=data_2016[0])
    df_2016['Year'] = 2016
    df_2016 = df_2016[['Country', 'Year', 'Happiness Score']]
    df_2016.columns = ['Country', 'Year', 'Score']
    df_2016['Score'] = df_2016['Score'].astype(float)

In [5]:
df_2016

                  Country  Year  Score
0                 Denmark  2016  7.526
1             Switzerland  2016  7.509
2                 Iceland  2016  7.501
3                  Norway  2016  7.498
4                 Finland  2016  7.413
5                  Canada  2016  7.404
6             Netherlands  2016  7.339
7             New Zealand  2016  7.334
8               Australia  2016  7.313
9                  Sweden  2016  7.291
10                 Israel  2016  7.267
11                Austria  2016  7.119
12          United States  2016  7.104
13             Costa Rica  2016  7.087
14            Puerto Rico  2016  7.039
15                Germany  2016  6.994
16                 Brazil  2016  6.952
17                Belgium  2016  6.929
18                Ireland  2016  6.907
19             Luxembourg  2016  6.871
20                 Mexico  2016  6.778
21              Singapore  2016  6.739
22         United Kingdom  2016  6.725
23                  Chile  2016  6.705
24                 Panama  2016  6.701
25              Argentina  2016  6.650
26         Czech Republic  2016  6.596
27   United Arab Emirates  2016  6.573
28                Uruguay  2016  6.545
29                  Malta  2016  6.488
..                    ...   ...    ...
127               Senegal  2016  4.219
128              Bulgaria  2016  4.217
129            Mauritania  2016  4.201
130              Zimbabwe  2016  4.193
131                Malawi  2016  4.156
132                 Sudan  2016  4.139
133                 Gabon  2016  4.121
134                  Mali  2016  4.073
135                 Haiti  2016  4.028
136              Botswana  2016  3.974
137               Comoros  2016  3.956
138           Ivory Coast  2016  3.916
139              Cambodia  2016  3.907
140                Angola  2016  3.866
141                 Niger  2016  3.856
142           South Sudan  2016  3.832
143                  Chad  2016  3.763
144          Burkina Faso  2016  3.739
145                Uganda  2016  3.739
146                 Yemen  2016  3.724
147            Madagascar  2016  3.695
148              Tanzania  2016  3.666
149               Liberia  2016  3.622
150                Guinea  2016  3.607
151                Rwanda  2016  3.515
152                 Benin  2016  3.484
153           Afghanistan  2016  3.360
154                  Togo  2016  3.303
155                 Syria  2016  3.069
156               Burundi  2016  2.905

[157 rows x 3 columns]

In [6]:
with open('2017.csv', 'r') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    data_2017 = list(spamreader)
    data_2017 = np.asarray(data_2017)
    df_2017 = pd.DataFrame(data=data_2017[1:], columns=data_2017[0])
    df_2017['Year'] = 2017
    df_2017 = df_2017[['Country', 'Year', 'Happiness.Score']]
    df_2017.columns = ['Country', 'Year', 'Score']
    df_2017['Score'] = df_2017['Score'].astype(float)

In [7]:
df_2017

                      Country  Year  Score
0                      Norway  2017  7.537
1                     Denmark  2017  7.522
2                     Iceland  2017  7.504
3                 Switzerland  2017  7.494
4                     Finland  2017  7.469
5                 Netherlands  2017  7.377
6                      Canada  2017  7.316
7                 New Zealand  2017  7.314
8                      Sweden  2017  7.284
9                   Australia  2017  7.284
10                     Israel  2017  7.213
11                 Costa Rica  2017  7.079
12                    Austria  2017  7.006
13              United States  2017  6.993
14                    Ireland  2017  6.977
15                    Germany  2017  6.951
16                    Belgium  2017  6.891
17                 Luxembourg  2017  6.863
18             United Kingdom  2017  6.714
19                      Chile  2017  6.652
20       United Arab Emirates  2017  6.648
21                     Brazil  2017  6.635
22             Czech Republic  2017  6.609
23                  Argentina  2017  6.599
24                     Mexico  2017  6.578
25                  Singapore  2017  6.572
26                      Malta  2017  6.527
27                    Uruguay  2017  6.454
28                  Guatemala  2017  6.454
29                     Panama  2017  6.452
..                        ...   ...    ...
125          Congo (Kinshasa)  2017  4.280
126                      Mali  2017  4.190
127               Ivory Coast  2017  4.180
128                  Cambodia  2017  4.168
129                     Sudan  2017  4.139
130                     Ghana  2017  4.120
131                   Ukraine  2017  4.096
132                    Uganda  2017  4.081
133              Burkina Faso  2017  4.032
134                     Niger  2017  4.028
135                    Malawi  2017  3.970
136                      Chad  2017  3.936
137                  Zimbabwe  2017  3.875
138                   Lesotho  2017  3.808
139                    Angola  2017  3.795
140               Afghanistan  2017  3.794
141                  Botswana  2017  3.766
142                     Benin  2017  3.657
143                Madagascar  2017  3.644
144                     Haiti  2017  3.603
145                     Yemen  2017  3.593
146               South Sudan  2017  3.591
147                   Liberia  2017  3.533
148                    Guinea  2017  3.507
149                      Togo  2017  3.495
150                    Rwanda  2017  3.471
151                     Syria  2017  3.462
152                  Tanzania  2017  3.349
153                   Burundi  2017  2.905
154  Central African Republic  2017  2.693

[155 rows x 3 columns]

In [8]:
df_score = pd.concat([df_2015, df_2016, df_2017])
df_score.sort_values(by=['Country', 'Year'], inplace=True)
df_count = df_score.groupby('Country').count()
df_score.reset_index(inplace=True, drop=True)

In [9]:
for country,row in df_count.iterrows():
    if(row['Year'] != 3):
        df_score.drop(df_score.loc[df_score['Country'] == country].index, inplace=True)
df_score.reset_index(inplace=True, drop=True)
df_score

                  Country  Year  Score
0             Afghanistan  2015  3.575
1             Afghanistan  2016  3.360
2             Afghanistan  2017  3.794
3                 Albania  2015  4.959
4                 Albania  2016  4.655
5                 Albania  2017  4.644
6                 Algeria  2015  5.605
7                 Algeria  2016  6.355
8                 Algeria  2017  5.872
9                  Angola  2015  4.033
10                 Angola  2016  3.866
11                 Angola  2017  3.795
12              Argentina  2015  6.574
13              Argentina  2016  6.650
14              Argentina  2017  6.599
15                Armenia  2015  4.350
16                Armenia  2016  4.360
17                Armenia  2017  4.376
18              Australia  2015  7.284
19              Australia  2016  7.313
20              Australia  2017  7.284
21                Austria  2015  7.200
22                Austria  2016  7.119
23                Austria  2017  7.006
24             Azerbaijan  2015  5.212
25             Azerbaijan  2016  5.291
26             Azerbaijan  2017  5.234
27                Bahrain  2015  5.960
28                Bahrain  2016  6.218
29                Bahrain  2017  6.087
..                    ...   ...    ...
408  United Arab Emirates  2015  6.901
409  United Arab Emirates  2016  6.573
410  United Arab Emirates  2017  6.648
411        United Kingdom  2015  6.867
412        United Kingdom  2016  6.725
413        United Kingdom  2017  6.714
414         United States  2015  7.119
415         United States  2016  7.104
416         United States  2017  6.993
417               Uruguay  2015  6.485
418               Uruguay  2016  6.545
419               Uruguay  2017  6.454
420            Uzbekistan  2015  6.003
421            Uzbekistan  2016  5.987
422            Uzbekistan  2017  5.971
423             Venezuela  2015  6.810
424             Venezuela  2016  6.084
425             Venezuela  2017  5.250
426               Vietnam  2015  5.360
427               Vietnam  2016  5.061
428               Vietnam  2017  5.074
429                 Yemen  2015  4.077
430                 Yemen  2016  3.724
431                 Yemen  2017  3.593
432                Zambia  2015  5.129
433                Zambia  2016  4.795
434                Zambia  2017  4.514
435              Zimbabwe  2015  4.610
436              Zimbabwe  2016  4.193
437              Zimbabwe  2017  3.875

[438 rows x 3 columns]

In [10]:
with open('fd1f9f89-994a-4025-b070-d32551a7c283_Data.csv', 'r') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    data = list(spamreader)
    data = np.asarray(data)
    df = pd.DataFrame(data=data[1:-1556], columns=data[0])
    df.drop(columns=['Country Code', 'Series Name'], axis=1, inplace=True)
    df.columns = ['Country', 'Series', '2013', '2014', '2015', '2016', '2017', '2018']
    df.loc[df['2015'] == '..', '2015'] = {}
    df.loc[df['2016'] == '..', '2016'] = {}
    df.loc[df['2017'] == '..', '2017'] = {}
    df['2015'] = df['2015'].astype(float)
    df['2016'] = df['2016'].astype(float)
    df['2017'] = df['2017'].astype(float)
    df = df[['Country', 'Series', '2015', '2016', '2017']]

In [11]:
df

,Country,Series,2015,2016,2017
0,Afghanistan,EG.ELC.ACCS.ZS,7.150000e+01,8.413714e+01,NaN
1,Afghanistan,SE.PRM.TENR,NaN,NaN,NaN
2,Afghanistan,NY.ADJ.NNTY.KD.ZG,NaN,NaN,NaN
3,Afghanistan,NY.ADJ.NNTY.PC.KD.ZG,NaN,NaN,NaN
4,Afghanistan,NY.ADJ.AEDU.GN.ZS,2.643742e+00,2.643742e+00,NaN
5,Afghanistan,NY.ADJ.ICTR.GN.ZS,-1.028845e+01,-1.087939e+01,NaN
6,Afghanistan,SP.POP.DPND,8.876873e+01,8.657093e+01,8.458728e+01
7,Afghanistan,SP.DYN.CBRT.IN,3.398000e+01,3.321400e+01,NaN
8,Afghanistan,per_si_allsi.cov_q1_tot,NaN,NaN,NaN
9,Afghanistan,per_si_allsi.cov_q5_tot,NaN,NaN,NaN
10,Afghanistan,per_allsp.cov_pop_tot,NaN,NaN,NaN
11,Afghanistan,per_sa_allsa.cov_pop_tot,NaN,NaN,NaN
12,Afghanistan,SP.DYN.CDRT.IN,6.924000e+00,6.747000e+00,NaN
13,Afghanistan,SE.XPD.PRIM.ZS,5.669549e+01,4.330205e+01,4.419060e+01
14,Afghanistan,SE.XPD.SECO.ZS,2.435630e+01,2.183389e+01,2.225369e+01
15,Afghanistan,GC.XPN.TOTL.GD.ZS,3.702257e+01,NaN,NaN
16,Afghanistan,SH.XPD.EHEX.CH.ZS,1.644546e+01,NaN,NaN
17,Afghanistan,NY.GDP.MKTP.CD,1.990711e+10,1.904636e+10,1.954398e+10
18,Afghanistan,NY.GDP.MKTP.KD.ZG,1.451315e+00,2.260314e+00,2.665292e+00
19,Afghanistan,NY.GDS.TOTL.ZS,2.948180e+00,4.954033e+00,7.155705e+00
20,Afghanistan,SE.ADT.1524.LT.ZS,NaN,NaN,NaN
21,Afghanistan,NV.IND.MANF.KD.ZG,4.093911e-01,1.087940e+00,7.487204e-01
22,Afghanistan,SH.DYN.NMRT,4.150000e+01,4.030000e+01,3.920000e+01
23,Afghanistan,SH.DYN.MORT,7.310000e+01,7.040000e+01,6.790000e+01
24,Afghanistan,SP.POP.TOTL,3.373649e+07,3.465603e+07,3.553008e+07
25,Afghanistan,SE.SEC.ENRL.TC.ZS,3.772088e+01,4.268464e+01,3.866756e+01
26,Afghanistan,SE.PRM.ENRL.TC.ZS,4.432877e+01,NaN,4.400995e+01
27,Afghanistan,EG.FEC.RNEW.ZS,1.842348e+01,NaN,NaN
28,Afghanistan,AG.SRF.TOTL.K2,6.528600e+05,6.528600e+05,6.528600e+05
29,Afghanistan,GC.TAX.TOTL.GD.ZS,7.585382e+00,NaN,NaN
...,...,...,...,...,...
7131,Zimbabwe,NY.ADJ.NNTY.PC.KD.ZG,6.350373e+00,-3.704330e+00,NaN
7132,Zimbabwe,NY.ADJ.AEDU.GN.ZS,1.910000e+00,1.910000e+00,NaN
7133,Zimbabwe,NY.ADJ.ICTR.GN.ZS,-1.058965e+01,-8.340989e-01,NaN
7134,Zimbabwe,SP.POP.DPND,7.951436e+01,7.919530e+01,7.865689e+01
7135,Zimbabwe,SP.DYN.CBRT.IN,3.393700e+01,3.314400e+01,NaN
7136,Zimbabwe,per_si_allsi.cov_q1_tot,NaN,NaN,NaN
7137,Zimbabwe,per_si_allsi.cov_q5_tot,NaN,NaN,NaN
7138,Zimbabwe,per_allsp.cov_pop_tot,NaN,NaN,NaN
7139,Zimbabwe,per_sa_allsa.cov_pop_tot,NaN,NaN,NaN
7140,Zimbabwe,SP.DYN.CDRT.IN,8.402000e+00,8.078000e+00,NaN
7141,Zimbabwe,SE.XPD.PRIM.ZS,NaN,NaN,NaN
7142,Zimbabwe,SE.XPD.SECO.ZS,NaN,NaN,NaN
7143,Zimbabwe,GC.XPN.TOTL.GD.ZS,NaN,NaN,NaN
7144,Zimbabwe,SH.XPD.EHEX.CH.ZS,2.425625e+01,NaN,NaN
7145,Zimbabwe,NY.GDP.MKTP.CD,1.996312e+10,2.054868e+10,2.204090e+10
7146,Zimbabwe,NY.GDP.MKTP.KD.ZG,1.779873e+00,7.558693e-01,4.704035e+00
7147,Zimbabwe,NY.GDS.TOTL.ZS,-8.392819e+00,-1.470590e+00,-1.010063e+00
7148,Zimbabwe,SE.ADT.1524.LT.ZS,NaN,NaN,NaN
7149,Zimbabwe,NV.IND.MANF.KD.ZG,1.999976e-01,5.550048e-01,1.300003e+00
7150,Zimbabwe,SH.DYN.NMRT,2.410000e+01,2.310000e+01,2.240000e+01
7151,Zimbabwe,SH.DYN.MORT,5.700000e+01,5.330000e+01,5.030000e+01
7152,Zimbabwe,SP.POP.TOTL,1.577745e+07,1.615036e+07,1.652990e+07
7153,Zimbabwe,SE.SEC.ENRL.TC.ZS,NaN,NaN,NaN
7154,Zimbabwe,SE.PRM.ENRL.TC.ZS,NaN,NaN,NaN
7155,Zimbabwe,EG.FEC.RNEW.ZS,8.179781e+01,NaN,NaN
7156,Zimbabwe,AG.SRF.TOTL.K2,3.907600e+05,3.907600e+05,3.907600e+05
7157,Zimbabwe,GC.TAX.TOTL.GD.ZS,NaN,NaN,NaN
7158,Zimbabwe,NE.TRD.GNFS.ZS,5.674881e+01,5.121902e+01,5.002830e+01
7159,Zimbabwe,SL.UEM.TOTL.NE.ZS,NaN,NaN,NaN
7160,Zimbabwe,FP.WPI.TOTL,NaN,NaN,NaN

In [12]:
countries = df['Country'].unique()
df_score.drop(df_score.loc[~df_score['Country'].isin(countries)].index, inplace=True)
df_score.reset_index(inplace=True, drop=True)
df_score

                  Country  Year  Score
0             Afghanistan  2015  3.575
1             Afghanistan  2016  3.360
2             Afghanistan  2017  3.794
3                 Albania  2015  4.959
4                 Albania  2016  4.655
5                 Albania  2017  4.644
6                 Algeria  2015  5.605
7                 Algeria  2016  6.355
8                 Algeria  2017  5.872
9                  Angola  2015  4.033
10                 Angola  2016  3.866
11                 Angola  2017  3.795
12              Argentina  2015  6.574
13              Argentina  2016  6.650
14              Argentina  2017  6.599
15                Armenia  2015  4.350
16                Armenia  2016  4.360
17                Armenia  2017  4.376
18              Australia  2015  7.284
19              Australia  2016  7.313
20              Australia  2017  7.284
21                Austria  2015  7.200
22                Austria  2016  7.119
23                Austria  2017  7.006
24             Azerbaijan  2015  5.212
25             Azerbaijan  2016  5.291
26             Azerbaijan  2017  5.234
27                Bahrain  2015  5.960
28                Bahrain  2016  6.218
29                Bahrain  2017  6.087
..                    ...   ...    ...
363                Uganda  2015  3.931
364                Uganda  2016  3.739
365                Uganda  2017  4.081
366               Ukraine  2015  4.681
367               Ukraine  2016  4.324
368               Ukraine  2017  4.096
369  United Arab Emirates  2015  6.901
370  United Arab Emirates  2016  6.573
371  United Arab Emirates  2017  6.648
372        United Kingdom  2015  6.867
373        United Kingdom  2016  6.725
374        United Kingdom  2017  6.714
375         United States  2015  7.119
376         United States  2016  7.104
377         United States  2017  6.993
378               Uruguay  2015  6.485
379               Uruguay  2016  6.545
380               Uruguay  2017  6.454
381            Uzbekistan  2015  6.003
382            Uzbekistan  2016  5.987
383            Uzbekistan  2017  5.971
384               Vietnam  2015  5.360
385               Vietnam  2016  5.061
386               Vietnam  2017  5.074
387                Zambia  2015  5.129
388                Zambia  2016  4.795
389                Zambia  2017  4.514
390              Zimbabwe  2015  4.610
391              Zimbabwe  2016  4.193
392              Zimbabwe  2017  3.875

[393 rows x 3 columns]

In [13]:
countries = df_score['Country'].unique()
for c in countries:
    indices = df.loc[df['Country'] == c].index
    if(indices.size == 0):
        continue
    
    c_ind = df_score.loc[df_score['Country'] == c].index
    for i in indices:
        df_score.at[c_ind[0], 'Ind '+str(i%33+1)] = df.loc[i]['2015']
        df_score.at[c_ind[1], 'Ind '+str(i%33+1)] = df.loc[i]['2016']
        df_score.at[c_ind[2], 'Ind '+str(i%33+1)] = df.loc[i]['2017']
df_score

,Country,Year,Score,Ind 1,Ind 2,Ind 3,Ind 4,Ind 5,Ind 6,Ind 7,...,Ind 24,Ind 25,Ind 26,Ind 27,Ind 28,Ind 29,Ind 30,Ind 31,Ind 32,Ind 33
0,Afghanistan,2015,3.575,71.500000,NaN,NaN,NaN,2.643742,-10.288447,88.768727,...,73.1,33736494.0,37.72088,44.32877,18.423477,6.528600e+05,7.585382,55.125527,NaN,NaN
1,Afghanistan,2016,3.360,84.137138,NaN,NaN,NaN,2.643742,-10.879392,86.570932,...,70.4,34656032.0,42.68464,NaN,NaN,6.528600e+05,NaN,47.659055,NaN,NaN
2,Afghanistan,2017,3.794,NaN,NaN,NaN,NaN,NaN,NaN,84.587278,...,67.9,35530081.0,38.66756,44.00995,NaN,6.528600e+05,NaN,51.236881,NaN,NaN
3,Albania,2015,4.959,100.000000,95.59661,4.618468,4.923567,3.227285,15.802049,44.016644,...,9.4,2880703.0,13.50589,18.61557,38.615210,2.875000e+04,18.515790,71.801016,17.080000,NaN
4,Albania,2016,4.655,100.000000,95.65855,3.196611,3.361734,3.227285,16.646368,44.001540,...,9.1,2876101.0,12.22137,18.19844,NaN,2.875000e+04,17.557178,74.669260,NaN,NaN
5,Albania,2017,4.644,NaN,97.06175,NaN,NaN,NaN,NaN,44.059506,...,8.8,2873457.0,11.60265,17.94478,NaN,2.875000e+04,18.860235,78.081456,13.750000,NaN
6,Algeria,2015,5.605,99.336708,99.26710,-2.760442,-4.609593,4.467196,36.803859,52.724919,...,24.9,39871528.0,NaN,23.83613,0.058959,2.381740e+06,NaN,59.695129,11.206100,NaN
7,Algeria,2016,6.355,99.439568,99.23121,-4.133982,-5.868105,4.467196,35.528237,53.907887,...,24.5,40606052.0,NaN,24.23550,NaN,2.381740e+06,NaN,55.892244,10.202400,NaN
8,Algeria,2017,5.872,NaN,99.44293,NaN,NaN,NaN,NaN,55.028217,...,24.0,41318142.0,NaN,24.22505,NaN,2.381740e+06,NaN,56.140352,13.570000,NaN
9,Angola,2015,4.033,42.000000,NaN,10.484883,6.761621,3.570000,-0.451391,97.576199,...,88.9,27859305.0,NaN,50.02951,49.568210,1.246700e+06,11.002019,62.888521,NaN,NaN
10,Angola,2016,3.866,40.520607,NaN,2.615014,-0.783083,3.570000,3.061931,97.274212,...,84.6,28813463.0,26.76619,NaN,NaN,1.246700e+06,9.732512,53.370155,NaN,NaN
11,Angola,2017,3.795,NaN,NaN,NaN,NaN,NaN,NaN,96.898518,...,81.1,29784193.0,NaN,NaN,NaN,1.246700e+06,9.223777,52.256821,NaN,NaN
12,Argentina,2015,6.574,99.995209,99.73430,2.193567,1.166753,5.057314,14.603558,56.549007,...,11.4,43417765.0,NaN,NaN,10.040078,2.780400e+06,12.336507,22.486226,NaN,NaN
13,Argentina,2016,6.650,100.000000,99.34152,-2.172171,-3.130795,5.057314,13.961236,56.542246,...,10.9,43847430.0,NaN,NaN,NaN,2.780400e+06,12.155505,26.121914,NaN,NaN
14,Argentina,2017,6.599,NaN,NaN,NaN,NaN,NaN,NaN,56.454765,...,10.4,44271041.0,NaN,NaN,NaN,2.780400e+06,11.047801,25.020836,8.347400,NaN
15,Armenia,2015,4.350,100.000000,92.80933,-2.106390,-2.466492,2.700193,17.426764,44.412259,...,14.0,2916950.0,NaN,NaN,15.792004,2.974000e+04,20.931221,71.593265,NaN,NaN
16,Armenia,2016,4.360,100.000000,92.32759,-2.182668,-2.445738,2.700193,15.864174,44.894943,...,13.3,2924816.0,NaN,NaN,NaN,2.974000e+04,21.277375,75.917880,NaN,NaN
17,Armenia,2017,4.376,NaN,92.39764,NaN,NaN,NaN,NaN,45.431545,...,12.6,2930450.0,NaN,NaN,NaN,2.974000e+04,20.764204,86.868094,17.704500,NaN
18,Australia,2015,7.284,100.000000,97.12010,1.401755,-0.072012,4.917263,23.602431,51.085458,...,3.8,23850784.0,NaN,NaN,9.180503,7.741220e+06,22.042810,41.547387,6.055700,NaN
19,Australia,2016,7.313,100.000000,96.78300,0.536793,-0.958232,4.917263,21.906456,51.863048,...,3.7,24210809.0,NaN,NaN,NaN,7.741220e+06,22.289293,40.771473,5.710800,NaN
20,Australia,2017,7.284,NaN,NaN,NaN,NaN,NaN,NaN,52.709336,...,3.5,24598933.0,NaN,NaN,NaN,7.741220e+06,22.213180,41.892970,5.593800,NaN
21,Austria,2015,7.200,100.000000,NaN,0.862118,-0.262225,5.218720,25.671325,49.165667,...,3.7,8642699.0,9.57663,10.58415,34.394992,8.387900e+04,26.779387,102.136010,5.722700,NaN
22,Austria,2016,7.119,100.000000,NaN,2.113296,1.014996,5.218720,26.025874,49.529837,...,3.6,8736668.0,9.41777,10.30374,NaN,8.387900e+04,25.666572,101.167013,6.013800,NaN
23,Austria,2017,7.006,NaN,NaN,NaN,NaN,NaN,NaN,49.909638,...,3.6,8809212.0,NaN,NaN,NaN,8.387900e+04,NaN,104.707772,5.499000,NaN
24,Azerbaijan,2015,5.212,100.000000,94.26275,NaN,NaN,2.607015,28.591094,40.151417,...,26.4,9649341.0,NaN,13.49787,2.310758,8.660000e+04,15.603163,72.601508,4.960000,NaN
25,Azerbaijan,2016,5.291,100.000000,94.96529,NaN,NaN,2.607015,22.817417,40.881603,...,24.6,9757812.0,7.12627,15.48619,NaN,8.660000e+04,NaN,90.077319,5.000000,NaN
26,Azerbaijan,2017,5.234,NaN,94.05446,NaN,NaN,NaN,NaN,41.433183,...,23.0,9862429.0,7.38650,15.45800,NaN,8.660000e+04,NaN,90.663591,5.000000,NaN
27,Bahrain,2015,5.960,100.000000,97.99544,8.208135,5.411306,2.910000,NaN,30.164307,...,7.6,1371855.0,9.86281,11.73164,0.000000,7.780000e+02,NaN,154.067393,NaN,NaN
28,Bahrain,2016,6.218,100.000000,97.90026,1.934934,-1.878477,2.910000,NaN,29.256542,...,7.5,1425171.0,9.79181,12.05837,NaN,7.780000e+02,NaN,139.553543,NaN,NaN
29,Bahrain,2017,6.087,NaN,98.86201,NaN,NaN,NaN,NaN,28.359541,...,7.3,1492584.0,10.14670,12.15924,NaN,7.780000e+02,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,Uganda,2015,3.931,18.500000,NaN,4.783343,1.360074,1.980319,17.541841,101.622700,...,55.3,40144870.0,NaN,42.91680,89.057949,2.415500e+05,12.928531,47.664421,NaN,NaN
364,Uganda,2016,3.739,26.700000,NaN,-3.310473,-6.440615,1.980319,20.204879,100.630768,...,51.6,41487965.0,NaN,42.72062,NaN,2.415500e+05,13.455770,47.114522,NaN,NaN
365,Uganda,2017,4.081,NaN,NaN,NaN,NaN,NaN,NaN,99.519325,...,49.0,42862958.0,NaN,42.65911,NaN,2.415500e+05,NaN,43.482034,9.440000,NaN
366,Ukraine,2015,4.681,100.000000,NaN,-10.268497,-9.373517,5.801227,15.907884,44.815602,...,9.4,45154029.0,6.97019,12.38447,4.144318,6.035500e+05,20.451365,107.806616,9.140000,NaN
367,Ukraine,2016,4.324,100.000000,NaN,3.858878,2.336341,5.801227,17.624340,45.759684,...,9.1,45004645.0,7.03673,12.75838,NaN,6.035500e+05,19.630120,105.521205,9.350000,NaN
368,Ukraine,2017,4.096,NaN,NaN,NaN,NaN,NaN,NaN,46.961035,...,8.8,44831159.0,7.20581,12.99453,NaN,6.035500e+05,20.040987,103.556247,9.510000,NaN
369,United Arab Emirates,2015,6.901,100.000000,95.97090,-8.358350,-9.193599,NaN,NaN,17.382455,...,8.7,9154302.0,NaN,23.61794,0.137108,8.360000e+04,0.057734,175.221308,NaN,NaN
370,United Arab Emirates,2016,6.573,100.000000,97.17865,-2.636028,-3.847194,NaN,NaN,17.608178,...,9.0,9269612.0,9.54885,24.52278,NaN,8.360000e+04,0.043495,176.747648,1.635502,NaN
371,United Arab Emirates,2017,6.648,NaN,NaN,NaN,NaN,NaN,NaN,17.701670,...,9.1,9400145.0,NaN,NaN,NaN,8.360000e+04,0.066984,172.810527,2.463000,NaN
372,United Kingdom,2015,6.867,100.000000,99.94197,2.915722,2.100819,5.660753,12.108289,55.535968,...,4.5,65128861.0,15.45905,NaN,8.711686,2.436100e+05,25.159723,56.476471,5.301200,NaN
373,United Kingdom,2016,6.725,100.000000,99.76344,2.303555,1.575679,5.660753,11.609867,56.174867,...,4.4,65595565.0,19.44776,15.05392,NaN,2.436100e+05,25.597116,58.582313,4.813200,NaN
374,United Kingdom,2017,6.714,NaN,NaN,NaN,NaN,NaN,NaN,56.809673,...,4.3,66022273.0,NaN,NaN,NaN,2.436100e+05,NaN,62.461831,4.334800,NaN
375,United States,2015,7.119,100.000000,94.60023,3.870160,3.088055,4.784507,18.959920,51.178902,...,6.8,321039839.0,14.69697,14.45723,8.716936,9.831510e+06,11.259124,27.890038,5.280000,NaN
376,United States,2016,7.104,100.000000,95.89206,0.974144,0.235399,4.784507,17.765126,51.652348,...,6.7,323405935.0,NaN,NaN,NaN,9.831510e+06,11.024841,26.579922,4.869200,NaN
377,United States,2017,6.993,NaN,NaN,NaN,NaN,NaN,NaN,52.268275,...,6.6,325719178.0,NaN,NaN,NaN,9.831510e+06,11.999733,NaN,4.355200,NaN
378,Uruguay,2015,6.485,99.709480,97.69772,0.034012,-0.315978,4.301524,17.344621,55.883555,...,8.9,3431552.0,NaN,11.76053,58.022041,1.762200e+05,18.509479,45.328241,7.487900,151.267296
379,Uruguay,2016,6.545,100.000000,98.34596,1.563743,1.196475,4.301524,18.212546,55.709145,...,8.6,3444006.0,NaN,11.13129,NaN,1.762200e+05,23.709305,41.310226,7.840600,156.337695
380,Uruguay,2017,6.454,NaN,NaN,NaN,NaN,NaN,NaN,55.555446,...,8.2,3456750.0,NaN,NaN,NaN,1.762200e+05,NaN,39.987824,7.889600,NaN
381,Uzbekistan,2015,6.003,100.000000,97.12497,4.207373,2.405487,9.374764,NaN,47.680344,...,25.6,31298900.0,10.69989,19.03192,2.970179,4.474000e+05,17.467265,49.324098,5.150000,NaN
382,Uzbekistan,2016,5.987,100.000000,97.50505,3.928007,2.136477,9.374764,NaN,47.729126,...,23.9,31847900.0,10.43487,20.42443,NaN,4.474000e+05,17.155928,51.153421,5.160000,NaN
383,Uzbekistan,2017,5.971,NaN,98.54778,NaN,NaN,NaN,NaN,48.045951,...,22.5,32387200.0,10.32977,21.15014,NaN,4.474000e+05,14.548632,68.518542,NaN,NaN
384,Vietnam,2015,5.360,100.000000,NaN,6.841246,5.669002,4.617752,28.816148,42.527839,...,21.6,93571567.0,NaN,19.22420,34.998570,3.312300e+05,NaN,178.767415,1.858500,NaN
385,Vietnam,2016,5.061,100.000000,NaN,9.754778,8.597096,4.617752,30.185763,42.858903,...,21.3,94569072.0,NaN,19.62995,NaN,3.312300e+05,NaN,184.686278,1.851500,NaN
386,Vietnam,2017,5.074,NaN,NaN,NaN,NaN,NaN,NaN,43.288199,...,20.9,95540800.0,NaN,19.64643,NaN,3.312300e+05,NaN,200.384580,1.886200,NaN
387,Zambia,2015,5.129,31.100000,NaN,NaN,NaN,1.060000,37.258926,91.865612,...,64.9,16100587.0,NaN,NaN,87.985452,7.526100e+05,16.830815,79.865155,NaN,NaN
388,Zambia,2016,4.795,27.219337,NaN,NaN,NaN,1.060000,34.289715,90.779663,...,62.4,16591390.0,NaN,NaN,NaN,7.526100e+05,14.937194,73.958574,NaN,NaN
389,Zambia,2017,4.514,NaN,NaN,NaN,NaN,NaN,NaN,89.613257,...,60.0,17094130.0,NaN,NaN,NaN,7.526100e+05,NaN,71.465880,NaN,NaN
390,Zimbabwe,2015,4.610,33.700000,NaN,8.874461,6.350373,1.910000,-10.589646,79.514364,...,57.0,15777451.0,NaN,NaN,81.797809,3.907600e+05,NaN,56.748811,NaN,NaN
391,Zimbabwe,2016,4.193,38.145138,NaN,-1.428315,-3.704330,1.910000,-0.834099,79.195304,...,53.3,16150362.0,NaN,NaN,NaN,3.907600e+05,NaN,51.219025,NaN,NaN
392,Zimbabwe,2017,3.875,NaN,NaN,NaN,NaN,NaN,NaN,78.656894,...,50.3,16529904.0,NaN,NaN,NaN,3.907600e+05,NaN,50.028296,NaN,NaN

In [14]:
df_score.interpolate(inplace=True)
df_score = df_score.reindex(index=df_score.index[::-1])
df_score.interpolate(inplace=True)
df = df_score.reindex(index=df_score.index[::-1])
df

,Country,Year,Score,Ind 1,Ind 2,Ind 3,Ind 4,Ind 5,Ind 6,Ind 7,...,Ind 24,Ind 25,Ind 26,Ind 27,Ind 28,Ind 29,Ind 30,Ind 31,Ind 32,Ind 33
0,Afghanistan,2015,3.575,71.500000,95.596610,4.618468,4.923567,2.643742,-10.288447,88.768727,...,73.1,33736494.0,37.720880,44.328770,18.423477,6.528600e+05,7.585382,55.125527,17.080000,136.123066
1,Afghanistan,2016,3.360,84.137138,95.596610,4.618468,4.923567,2.643742,-10.879392,86.570932,...,70.4,34656032.0,42.684640,44.169360,25.154055,6.528600e+05,11.228852,47.659055,17.080000,136.123066
2,Afghanistan,2017,3.794,92.068569,95.596610,4.618468,4.923567,2.935513,2.461328,84.587278,...,67.9,35530081.0,38.667560,44.009950,31.884633,6.528600e+05,14.872321,51.236881,17.080000,136.123066
3,Albania,2015,4.959,100.000000,95.596610,4.618468,4.923567,3.227285,15.802049,44.016644,...,9.4,2880703.0,13.505890,18.615570,38.615210,2.875000e+04,18.515790,71.801016,17.080000,136.123066
4,Albania,2016,4.655,100.000000,95.658550,3.196611,3.361734,3.227285,16.646368,44.001540,...,9.1,2876101.0,12.221370,18.198440,25.763127,2.875000e+04,17.557178,74.669260,15.415000,136.123066
5,Albania,2017,4.644,99.668354,97.061750,0.218084,-0.623930,3.847240,26.725113,44.059506,...,8.8,2873457.0,11.602650,17.944780,12.911043,2.875000e+04,18.860235,78.081456,13.750000,136.123066
6,Algeria,2015,5.605,99.336708,99.267100,-2.760442,-4.609593,4.467196,36.803859,52.724919,...,24.9,39871528.0,14.635358,23.836130,0.058959,2.381740e+06,16.895681,59.695129,11.206100,136.123066
7,Algeria,2016,6.355,99.439568,99.231210,-4.133982,-5.868105,4.467196,35.528237,53.907887,...,24.5,40606052.0,17.668066,24.235500,16.562043,2.381740e+06,14.931127,55.892244,10.202400,136.123066
8,Algeria,2017,5.872,70.719784,99.442930,3.175451,0.446758,4.018598,17.538423,55.028217,...,24.0,41318142.0,20.700774,24.225050,33.065126,2.381740e+06,12.966573,56.140352,13.570000,136.123066
9,Angola,2015,4.033,42.000000,99.515772,10.484883,6.761621,3.570000,-0.451391,97.576199,...,88.9,27859305.0,23.733482,50.029510,49.568210,1.246700e+06,11.002019,62.888521,12.699566,136.123066
10,Angola,2016,3.866,40.520607,99.588615,2.615014,-0.783083,3.570000,3.061931,97.274212,...,84.6,28813463.0,26.766190,46.742397,36.392166,1.246700e+06,9.732512,53.370155,11.829133,136.123066
11,Angola,2017,3.795,70.257908,99.661458,2.404290,0.191835,4.313657,8.832744,96.898518,...,81.1,29784193.0,25.203503,43.455283,23.216122,1.246700e+06,9.223777,52.256821,10.958700,136.123066
12,Argentina,2015,6.574,99.995209,99.734300,2.193567,1.166753,5.057314,14.603558,56.549007,...,11.4,43417765.0,23.640815,40.168170,10.040078,2.780400e+06,12.336507,22.486226,10.088266,136.123066
13,Argentina,2016,6.650,100.000000,99.341520,-2.172171,-3.130795,5.057314,13.961236,56.542246,...,10.9,43847430.0,22.078128,36.881057,11.957386,2.780400e+06,12.155505,26.121914,9.217833,136.123066
14,Argentina,2017,6.599,100.000000,96.075425,-2.139281,-2.798643,3.878753,15.694000,56.454765,...,10.4,44271041.0,20.515441,33.593943,13.874695,2.780400e+06,11.047801,25.020836,8.347400,136.123066
15,Armenia,2015,4.350,100.000000,92.809330,-2.106390,-2.466492,2.700193,17.426764,44.412259,...,14.0,2916950.0,18.952754,30.306830,15.792004,2.974000e+04,20.931221,71.593265,11.466433,136.123066
16,Armenia,2016,4.360,100.000000,92.327590,-2.182668,-2.445738,2.700193,15.864174,44.894943,...,13.3,2924816.0,17.390066,27.019717,13.588170,2.974000e+04,21.277375,75.917880,14.585467,136.123066
17,Armenia,2017,4.376,100.000000,92.397640,-0.390456,-1.258875,3.808728,19.733303,45.431545,...,12.6,2930450.0,15.827379,23.732603,11.384337,2.974000e+04,20.764204,86.868094,17.704500,136.123066
18,Australia,2015,7.284,100.000000,97.120100,1.401755,-0.072012,4.917263,23.602431,51.085458,...,3.8,23850784.0,14.264692,20.445490,9.180503,7.741220e+06,22.042810,41.547387,6.055700,136.123066
19,Australia,2016,7.313,100.000000,96.783000,0.536793,-0.958232,4.917263,21.906456,51.863048,...,3.7,24210809.0,12.702005,17.158377,17.585333,7.741220e+06,22.289293,40.771473,5.710800,136.123066
20,Australia,2017,7.284,100.000000,96.278950,0.699455,-0.610229,5.067992,23.788891,52.709336,...,3.5,24598933.0,11.139317,13.871263,25.990162,7.741220e+06,22.213180,41.892970,5.593800,136.123066
21,Austria,2015,7.200,100.000000,95.774900,0.862118,-0.262225,5.218720,25.671325,49.165667,...,3.7,8642699.0,9.576630,10.584150,34.394992,8.387900e+04,26.779387,102.136010,5.722700,136.123066
22,Austria,2016,7.119,100.000000,95.270850,2.113296,1.014996,5.218720,26.025874,49.529837,...,3.6,8736668.0,9.417770,10.303740,23.700247,8.387900e+04,25.666572,101.167013,6.013800,136.123066
23,Austria,2017,7.006,100.000000,94.766800,3.332264,1.894258,3.912868,27.308484,49.909638,...,3.6,8809212.0,8.653937,11.900805,13.005502,8.387900e+04,20.634868,104.707772,5.499000,136.123066
24,Azerbaijan,2015,5.212,100.000000,94.262750,4.551232,2.773520,2.607015,28.591094,40.151417,...,26.4,9649341.0,7.890103,13.497870,2.310758,8.660000e+04,15.603163,72.601508,4.960000,136.123066
25,Azerbaijan,2016,5.291,100.000000,94.965290,5.770199,3.652782,2.607015,22.817417,40.881603,...,24.6,9757812.0,7.126270,15.486190,1.540505,8.660000e+04,14.419027,90.077319,5.000000,136.123066
26,Azerbaijan,2017,5.234,100.000000,94.054460,6.989167,4.532044,2.758508,25.024289,41.433183,...,23.0,9862429.0,7.386500,15.458000,0.770253,8.660000e+04,13.234892,90.663591,5.000000,136.123066
27,Bahrain,2015,5.960,100.000000,97.995440,8.208135,5.411306,2.910000,27.231161,30.164307,...,7.6,1371855.0,9.862810,11.731640,0.000000,7.780000e+02,12.050756,154.067393,4.870000,136.123066
28,Bahrain,2016,6.218,100.000000,97.900260,1.934934,-1.878477,2.910000,29.438032,29.256542,...,7.5,1425171.0,9.791810,12.058370,11.582356,7.780000e+02,10.866620,139.553543,4.740000,136.123066
29,Bahrain,2017,6.087,84.102341,98.862010,3.994640,1.497268,2.324336,31.644904,28.359541,...,7.3,1492584.0,10.146700,12.159240,23.164713,7.780000e+02,9.682485,90.819770,4.610000,136.123066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,Uganda,2015,3.931,18.500000,95.136098,4.783343,1.360074,1.980319,17.541841,101.622700,...,55.3,40144870.0,10.797750,42.916800,89.057949,2.415500e+05,12.928531,47.664421,9.899733,134.225135
364,Uganda,2016,3.739,26.700000,95.275232,-3.310473,-6.440615,1.980319,20.204879,100.630768,...,51.6,41487965.0,9.521897,42.720620,60.753405,2.415500e+05,13.455770,47.114522,9.669866,135.361279
365,Uganda,2017,4.081,63.350000,95.414365,-6.789485,-7.907066,3.890773,18.056382,99.519325,...,49.0,42862958.0,8.246043,42.659110,32.448862,2.415500e+05,16.953568,43.482034,9.440000,136.497423
366,Ukraine,2015,4.681,100.000000,95.553499,-10.268497,-9.373517,5.801227,15.907884,44.815602,...,9.4,45154029.0,6.970190,12.384470,4.144318,6.035500e+05,20.451365,107.806616,9.140000,137.633567
367,Ukraine,2016,4.324,100.000000,95.692633,3.858878,2.336341,5.801227,17.624340,45.759684,...,9.1,45004645.0,7.036730,12.758380,2.808581,6.035500e+05,19.630120,105.521205,9.350000,138.769711
368,Ukraine,2017,4.096,100.000000,95.831766,-2.249736,-3.428629,5.773132,16.521130,46.961035,...,8.8,44831159.0,7.205810,12.994530,1.472845,6.035500e+05,20.040987,103.556247,9.510000,139.905855
369,United Arab Emirates,2015,6.901,100.000000,95.970900,-8.358350,-9.193599,5.745038,15.417920,17.382455,...,8.7,9154302.0,8.377330,23.617940,0.137108,8.360000e+04,0.057734,175.221308,5.572751,141.041999
370,United Arab Emirates,2016,6.573,100.000000,97.178650,-2.636028,-3.847194,5.716943,14.314710,17.608178,...,9.0,9269612.0,9.548850,24.522780,2.995301,8.360000e+04,0.043495,176.747648,1.635502,142.178143
371,United Arab Emirates,2017,6.648,100.000000,98.560310,0.139847,-0.873187,5.688848,13.211499,17.701670,...,9.1,9400145.0,12.503950,21.366493,5.853493,8.360000e+04,0.066984,172.810527,2.463000,143.314287
372,United Kingdom,2015,6.867,100.000000,99.941970,2.915722,2.100819,5.660753,12.108289,55.535968,...,4.5,65128861.0,15.459050,18.210207,8.711686,2.436100e+05,25.159723,56.476471,5.301200,144.450431
373,United Kingdom,2016,6.725,100.000000,99.763440,2.303555,1.575679,5.660753,11.609867,56.174867,...,4.4,65595565.0,19.447760,15.053920,8.713436,2.436100e+05,25.597116,58.582313,4.813200,145.586576
374,United Kingdom,2017,6.714,100.000000,97.181835,3.086858,2.331867,5.222630,15.284894,56.809673,...,4.3,66022273.0,17.072365,14.755575,8.715186,2.436100e+05,18.428120,62.461831,4.334800,146.722720
375,United States,2015,7.119,100.000000,94.600230,3.870160,3.088055,4.784507,18.959920,51.178902,...,6.8,321039839.0,14.696970,14.457230,8.716936,9.831510e+06,11.259124,27.890038,5.280000,147.858864
376,United States,2016,7.104,100.000000,95.892060,0.974144,0.235399,4.784507,17.765126,51.652348,...,6.7,323405935.0,14.030790,13.558330,25.151971,9.831510e+06,11.024841,26.579922,4.869200,148.995008
377,United States,2017,6.993,99.854740,96.794890,0.504078,-0.040289,4.543016,17.554874,52.268275,...,6.6,325719178.0,13.364610,12.659430,41.587006,9.831510e+06,11.999733,35.954082,4.355200,150.131152
378,Uruguay,2015,6.485,99.709480,97.697720,0.034012,-0.315978,4.301524,17.344621,55.883555,...,8.9,3431552.0,12.698430,11.760530,58.022041,1.762200e+05,18.509479,45.328241,7.487900,151.267296
379,Uruguay,2016,6.545,100.000000,98.345960,1.563743,1.196475,4.301524,18.212546,55.709145,...,8.6,3444006.0,12.032250,11.131290,39.671420,1.762200e+05,23.709305,41.310226,7.840600,156.337695
380,Uruguay,2017,6.454,100.000000,97.735465,2.885558,1.800981,6.838144,20.333266,55.555446,...,8.2,3456750.0,11.366070,15.081605,21.320800,1.762200e+05,20.588285,39.987824,7.889600,156.337695
381,Uzbekistan,2015,6.003,100.000000,97.124970,4.207373,2.405487,9.374764,22.453987,47.680344,...,25.6,31298900.0,10.699890,19.031920,2.970179,4.474000e+05,17.467265,49.324098,5.150000,156.337695
382,Uzbekistan,2016,5.987,100.000000,97.505050,3.928007,2.136477,9.374764,24.574707,47.729126,...,23.9,31847900.0,10.434870,20.424430,13.646309,4.474000e+05,17.155928,51.153421,5.160000,156.337695
383,Uzbekistan,2017,5.971,100.000000,98.547780,5.384627,3.902739,6.996258,26.695427,48.045951,...,22.5,32387200.0,10.329770,21.150140,24.322439,4.474000e+05,14.548632,68.518542,3.509250,156.337695
384,Vietnam,2015,5.360,100.000000,98.547780,6.841246,5.669002,4.617752,28.816148,42.527839,...,21.6,93571567.0,10.329770,19.224200,34.998570,3.312300e+05,15.119178,178.767415,1.858500,156.337695
385,Vietnam,2016,5.061,100.000000,98.547780,9.754778,8.597096,4.617752,30.185763,42.858903,...,21.3,94569072.0,10.329770,19.629950,52.660864,3.312300e+05,15.689724,184.686278,1.851500,156.337695
386,Vietnam,2017,5.074,65.550000,98.547780,9.578714,8.147751,2.838876,33.722344,43.288199,...,20.9,95540800.0,10.329770,19.646430,70.323158,3.312300e+05,16.260269,200.384580,1.886200,156.337695
387,Zambia,2015,5.129,31.100000,98.547780,9.402651,7.698407,1.060000,37.258926,91.865612,...,64.9,16100587.0,10.329770,19.646430,87.985452,7.526100e+05,16.830815,79.865155,1.886200,156.337695
388,Zambia,2016,4.795,27.219337,98.547780,9.226587,7.249062,1.060000,34.289715,90.779663,...,62.4,16591390.0,10.329770,19.646430,85.922904,7.526100e+05,14.937194,73.958574,1.886200,156.337695
389,Zambia,2017,4.514,30.459669,98.547780,9.050524,6.799718,1.485000,11.850035,89.613257,...,60.0,17094130.0,10.329770,19.646430,83.860356,7.526100e+05,14.937194,71.465880,1.886200,156.337695
390,Zimbabwe,2015,4.610,33.700000,98.547780,8.874461,6.350373,1.910000,-10.589646,79.514364,...,57.0,15777451.0,10.329770,19.646430,81.797809,3.907600e+05,14.937194,56.748811,1.886200,156.337695
391,Zimbabwe,2016,4.193,38.145138,98.547780,-1.428315,-3.704330,1.910000,-0.834099,79.195304,...,53.3,16150362.0,10.329770,19.646430,81.797809,3.907600e+05,14.937194,51.219025,1.886200,156.337695
392,Zimbabwe,2017,3.875,38.145138,98.547780,-1.428315,-3.704330,1.910000,-0.834099,78.656894,...,50.3,16529904.0,10.329770,19.646430,81.797809,3.907600e+05,14.937194,50.028296,1.886200,156.337695

In [15]:
#Saving as pickle file
df.to_pickle('happiness_data.pkl')

In [16]:
#Saving as CSV file
df.to_csv('happiness_data.csv', sep=',', encoding='utf-8')